# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
warnings_are_errors: true
sudo: required
cache: packages

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev \
    libudunits2-dev libv8-3.14-dev libjq-dev libprotobuf-dev
    - R -e "install.packages('geojsonio', dependencies=TRUE)"

