# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
warnings_are_errors: true
sudo: required
cache: packages

r_packages:
  - pkgdown
r_github_packages:
  - jimhester/covr

addons:
  apt:
    packages:
      - libgdal-dev
      - libgeos-dev
      - libssl-dev
      - xclip

# copy from
# https://github.com/mdlincoln/clipr/blob/master/.travis.yml
env: TRAVIS_CLIP=xclip DISPLAY=:99.0 CLIPR_ALLOW=TRUE
# see https://github.com/mdlincoln/clipr/issues/21
# Ensure xclip can still run headlessly
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - if [ "$TRAVIS_CLIP" == "xclip" ]; then uptime | xclip -i -sel p -f | xclip -i -sel c; xclip -o -sel clipboard; fi

before_install:
  - nvm install 8.10.0
  - npm i -g create-react-app

after_success:
  - Rscript -e "covr::codecov()"

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
