# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
warnings_are_errors: true
sudo: required
cache: packages

r_github_packages:
  - jimhester/covr
r_check_args: --no-build-vignettes

addons:
  apt:
    packages:
      - libudunits2-dev # paper.Rmd see travis builds/508333361#L1622
      - libgdal-dev
      - libgeos-dev
      - libssl-dev
      - xclip
      - libsodium-dev
      - libharfbuzz-dev
      - libfribidi-dev

# copy from
# https://github.com/mdlincoln/clipr/blob/master/.travis.yml
env: TRAVIS_CLIP=xclip DISPLAY=:99.0 CLIPR_ALLOW=TRUE
# see https://github.com/mdlincoln/clipr/issues/21
# Ensure xclip can still run headlessly
services:
  - xvfb
before_script:
  - if [ "$TRAVIS_CLIP" == "xclip" ]; then uptime | xclip -i -sel p -f | xclip -i -sel c; xclip -o -sel clipboard; fi

before_install:
  - nvm install 12.18.3
  - npm i -g create-react-app
  - Rscript -e 'install.packages("ragg")'
  - Rscript -e 'install.packages("pkgdown")'

after_success:
  - Rscript -e "covr::codecov()"

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
